/* File: dpssmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Tue Feb 12 18:49:53 2013
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *dpss_error;
static PyObject *dpss_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(dpss_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = dpss_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = dpss_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(DPSS,DPSS)(int*,int*,int*,double*,double*,double*,int*,double*,double*,double*,double*,int*);
extern void F_FUNC(SYTOEP,SYTOEP)(int*,double*,double*,double*,double*,int*);
extern void F_FUNC(SPOL,SPOL)(int*,double*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ DPSS ************************************/
static char doc_f2py_rout_dpss_DPSS[] = "\
Function signature:\n\
  V,SIG,TOTIT,IFAULT = DPSS(NMAX,KMAX,W,SINES,VOLD,U,SCR1,[N])\n\
Required arguments:\n"
"  NMAX : input int\n"
"  KMAX : input int\n"
"  W : input float\n"
"  SINES : input rank-1 array('d') with bounds (N)\n"
"  VOLD : input rank-1 array('d') with bounds (N)\n"
"  U : input rank-1 array('d') with bounds (N)\n"
"  SCR1 : input rank-1 array('d') with bounds (N)\n"
"Optional arguments:\n"
"  N := len(SINES) input int\n"
"Return objects:\n"
"  V : rank-2 array('d') with bounds (NMAX,KMAX + 1)\n"
"  SIG : rank-1 array('d') with bounds (KMAX + 1)\n"
"  TOTIT : int\n"
"  IFAULT : int";
/* extern void F_FUNC(DPSS,DPSS)(int*,int*,int*,double*,double*,double*,int*,double*,double*,double*,double*,int*); */
static PyObject *f2py_rout_dpss_DPSS(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,double*,double*,double*,int*,double*,double*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int NMAX = 0;
  PyObject *NMAX_capi = Py_None;
  int KMAX = 0;
  PyObject *KMAX_capi = Py_None;
  int N = 0;
  PyObject *N_capi = Py_None;
  double W = 0;
  PyObject *W_capi = Py_None;
  double *V = NULL;
  npy_intp V_Dims[2] = {-1, -1};
  const int V_Rank = 2;
  PyArrayObject *capi_V_tmp = NULL;
  int capi_V_intent = 0;
  double *SIG = NULL;
  npy_intp SIG_Dims[1] = {-1};
  const int SIG_Rank = 1;
  PyArrayObject *capi_SIG_tmp = NULL;
  int capi_SIG_intent = 0;
  int TOTIT = 0;
  double *SINES = NULL;
  npy_intp SINES_Dims[1] = {-1};
  const int SINES_Rank = 1;
  PyArrayObject *capi_SINES_tmp = NULL;
  int capi_SINES_intent = 0;
  PyObject *SINES_capi = Py_None;
  double *VOLD = NULL;
  npy_intp VOLD_Dims[1] = {-1};
  const int VOLD_Rank = 1;
  PyArrayObject *capi_VOLD_tmp = NULL;
  int capi_VOLD_intent = 0;
  PyObject *VOLD_capi = Py_None;
  double *U = NULL;
  npy_intp U_Dims[1] = {-1};
  const int U_Rank = 1;
  PyArrayObject *capi_U_tmp = NULL;
  int capi_U_intent = 0;
  PyObject *U_capi = Py_None;
  double *SCR1 = NULL;
  npy_intp SCR1_Dims[1] = {-1};
  const int SCR1_Rank = 1;
  PyArrayObject *capi_SCR1_tmp = NULL;
  int capi_SCR1_intent = 0;
  PyObject *SCR1_capi = Py_None;
  int IFAULT = 0;
  static char *capi_kwlist[] = {"NMAX","KMAX","W","SINES","VOLD","U","SCR1","N",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO|O:dpss.DPSS",\
    capi_kwlist,&NMAX_capi,&KMAX_capi,&W_capi,&SINES_capi,&VOLD_capi,&U_capi,&SCR1_capi,&N_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable NMAX */
    f2py_success = int_from_pyobj(&NMAX,NMAX_capi,"dpss.DPSS() 1st argument (NMAX) can't be converted to int");
  if (f2py_success) {
  /* Processing variable SINES */
  ;
  capi_SINES_intent |= F2PY_INTENT_IN;
  capi_SINES_tmp = array_from_pyobj(PyArray_DOUBLE,SINES_Dims,SINES_Rank,capi_SINES_intent,SINES_capi);
  if (capi_SINES_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(dpss_error,"failed in converting 4th argument `SINES' of dpss.DPSS to C/Fortran array" );
  } else {
    SINES = (double *)(capi_SINES_tmp->data);

  /* Processing variable IFAULT */
  /* Processing variable W */
    f2py_success = double_from_pyobj(&W,W_capi,"dpss.DPSS() 3rd argument (W) can't be converted to double");
  if (f2py_success) {
  /* Processing variable TOTIT */
  /* Processing variable KMAX */
    f2py_success = int_from_pyobj(&KMAX,KMAX_capi,"dpss.DPSS() 2nd argument (KMAX) can't be converted to int");
  if (f2py_success) {
  /* Processing variable V */
  V_Dims[0]=NMAX,V_Dims[1]=KMAX + 1;
  capi_V_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_V_tmp = array_from_pyobj(PyArray_DOUBLE,V_Dims,V_Rank,capi_V_intent,Py_None);
  if (capi_V_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(dpss_error,"failed in converting hidden `V' of dpss.DPSS to C/Fortran array" );
  } else {
    V = (double *)(capi_V_tmp->data);

  /* Processing variable SIG */
  SIG_Dims[0]=KMAX + 1;
  capi_SIG_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_SIG_tmp = array_from_pyobj(PyArray_DOUBLE,SIG_Dims,SIG_Rank,capi_SIG_intent,Py_None);
  if (capi_SIG_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(dpss_error,"failed in converting hidden `SIG' of dpss.DPSS to C/Fortran array" );
  } else {
    SIG = (double *)(capi_SIG_tmp->data);

  /* Processing variable N */
  if (N_capi == Py_None) N = len(SINES); else
    f2py_success = int_from_pyobj(&N,N_capi,"dpss.DPSS() 1st keyword (N) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(SINES)>=N,"len(SINES)>=N","1st keyword N","DPSS:N=%d",N) {
  /* Processing variable U */
  U_Dims[0]=N;
  capi_U_intent |= F2PY_INTENT_IN;
  capi_U_tmp = array_from_pyobj(PyArray_DOUBLE,U_Dims,U_Rank,capi_U_intent,U_capi);
  if (capi_U_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(dpss_error,"failed in converting 6th argument `U' of dpss.DPSS to C/Fortran array" );
  } else {
    U = (double *)(capi_U_tmp->data);

  /* Processing variable SCR1 */
  SCR1_Dims[0]=N;
  capi_SCR1_intent |= F2PY_INTENT_IN;
  capi_SCR1_tmp = array_from_pyobj(PyArray_DOUBLE,SCR1_Dims,SCR1_Rank,capi_SCR1_intent,SCR1_capi);
  if (capi_SCR1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(dpss_error,"failed in converting 7th argument `SCR1' of dpss.DPSS to C/Fortran array" );
  } else {
    SCR1 = (double *)(capi_SCR1_tmp->data);

  /* Processing variable VOLD */
  VOLD_Dims[0]=N;
  capi_VOLD_intent |= F2PY_INTENT_IN;
  capi_VOLD_tmp = array_from_pyobj(PyArray_DOUBLE,VOLD_Dims,VOLD_Rank,capi_VOLD_intent,VOLD_capi);
  if (capi_VOLD_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(dpss_error,"failed in converting 5th argument `VOLD' of dpss.DPSS to C/Fortran array" );
  } else {
    VOLD = (double *)(capi_VOLD_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&NMAX,&KMAX,&N,&W,V,SIG,&TOTIT,SINES,VOLD,U,SCR1,&IFAULT);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNii",capi_V_tmp,capi_SIG_tmp,TOTIT,IFAULT);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_VOLD_tmp!=VOLD_capi) {
    Py_XDECREF(capi_VOLD_tmp); }
  }  /*if (capi_VOLD_tmp == NULL) ... else of VOLD*/
  /* End of cleaning variable VOLD */
  if((PyObject *)capi_SCR1_tmp!=SCR1_capi) {
    Py_XDECREF(capi_SCR1_tmp); }
  }  /*if (capi_SCR1_tmp == NULL) ... else of SCR1*/
  /* End of cleaning variable SCR1 */
  if((PyObject *)capi_U_tmp!=U_capi) {
    Py_XDECREF(capi_U_tmp); }
  }  /*if (capi_U_tmp == NULL) ... else of U*/
  /* End of cleaning variable U */
  } /*CHECKSCALAR(len(SINES)>=N)*/
  } /*if (f2py_success) of N*/
  /* End of cleaning variable N */
  }  /*if (capi_SIG_tmp == NULL) ... else of SIG*/
  /* End of cleaning variable SIG */
  }  /*if (capi_V_tmp == NULL) ... else of V*/
  /* End of cleaning variable V */
  } /*if (f2py_success) of KMAX*/
  /* End of cleaning variable KMAX */
  /* End of cleaning variable TOTIT */
  } /*if (f2py_success) of W*/
  /* End of cleaning variable W */
  /* End of cleaning variable IFAULT */
  if((PyObject *)capi_SINES_tmp!=SINES_capi) {
    Py_XDECREF(capi_SINES_tmp); }
  }  /*if (capi_SINES_tmp == NULL) ... else of SINES*/
  /* End of cleaning variable SINES */
  } /*if (f2py_success) of NMAX*/
  /* End of cleaning variable NMAX */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of DPSS ********************************/

/*********************************** SYTOEP ***********************************/
static char doc_f2py_rout_dpss_SYTOEP[] = "\
Function signature:\n\
  SYTOEP(R,G,F,W,IFAULT,[N])\n\
Required arguments:\n"
"  R : input rank-1 array('d') with bounds (N)\n"
"  G : input rank-1 array('d') with bounds (N)\n"
"  F : input rank-1 array('d') with bounds (N)\n"
"  W : input rank-1 array('d') with bounds (N)\n"
"  IFAULT : input int\n"
"Optional arguments:\n"
"  N := len(R) input int";
/* extern void F_FUNC(SYTOEP,SYTOEP)(int*,double*,double*,double*,double*,int*); */
static PyObject *f2py_rout_dpss_SYTOEP(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int N = 0;
  PyObject *N_capi = Py_None;
  double *R = NULL;
  npy_intp R_Dims[1] = {-1};
  const int R_Rank = 1;
  PyArrayObject *capi_R_tmp = NULL;
  int capi_R_intent = 0;
  PyObject *R_capi = Py_None;
  double *G = NULL;
  npy_intp G_Dims[1] = {-1};
  const int G_Rank = 1;
  PyArrayObject *capi_G_tmp = NULL;
  int capi_G_intent = 0;
  PyObject *G_capi = Py_None;
  double *F = NULL;
  npy_intp F_Dims[1] = {-1};
  const int F_Rank = 1;
  PyArrayObject *capi_F_tmp = NULL;
  int capi_F_intent = 0;
  PyObject *F_capi = Py_None;
  double *W = NULL;
  npy_intp W_Dims[1] = {-1};
  const int W_Rank = 1;
  PyArrayObject *capi_W_tmp = NULL;
  int capi_W_intent = 0;
  PyObject *W_capi = Py_None;
  int IFAULT = 0;
  PyObject *IFAULT_capi = Py_None;
  static char *capi_kwlist[] = {"R","G","F","W","IFAULT","N",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|O:dpss.SYTOEP",\
    capi_kwlist,&R_capi,&G_capi,&F_capi,&W_capi,&IFAULT_capi,&N_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable IFAULT */
    f2py_success = int_from_pyobj(&IFAULT,IFAULT_capi,"dpss.SYTOEP() 5th argument (IFAULT) can't be converted to int");
  if (f2py_success) {
  /* Processing variable R */
  ;
  capi_R_intent |= F2PY_INTENT_IN;
  capi_R_tmp = array_from_pyobj(PyArray_DOUBLE,R_Dims,R_Rank,capi_R_intent,R_capi);
  if (capi_R_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(dpss_error,"failed in converting 1st argument `R' of dpss.SYTOEP to C/Fortran array" );
  } else {
    R = (double *)(capi_R_tmp->data);

  /* Processing variable N */
  if (N_capi == Py_None) N = len(R); else
    f2py_success = int_from_pyobj(&N,N_capi,"dpss.SYTOEP() 1st keyword (N) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(R)>=N,"len(R)>=N","1st keyword N","SYTOEP:N=%d",N) {
  /* Processing variable W */
  W_Dims[0]=N;
  capi_W_intent |= F2PY_INTENT_IN;
  capi_W_tmp = array_from_pyobj(PyArray_DOUBLE,W_Dims,W_Rank,capi_W_intent,W_capi);
  if (capi_W_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(dpss_error,"failed in converting 4th argument `W' of dpss.SYTOEP to C/Fortran array" );
  } else {
    W = (double *)(capi_W_tmp->data);

  /* Processing variable G */
  G_Dims[0]=N;
  capi_G_intent |= F2PY_INTENT_IN;
  capi_G_tmp = array_from_pyobj(PyArray_DOUBLE,G_Dims,G_Rank,capi_G_intent,G_capi);
  if (capi_G_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(dpss_error,"failed in converting 2nd argument `G' of dpss.SYTOEP to C/Fortran array" );
  } else {
    G = (double *)(capi_G_tmp->data);

  /* Processing variable F */
  F_Dims[0]=N;
  capi_F_intent |= F2PY_INTENT_IN;
  capi_F_tmp = array_from_pyobj(PyArray_DOUBLE,F_Dims,F_Rank,capi_F_intent,F_capi);
  if (capi_F_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(dpss_error,"failed in converting 3rd argument `F' of dpss.SYTOEP to C/Fortran array" );
  } else {
    F = (double *)(capi_F_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&N,R,G,F,W,&IFAULT);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_F_tmp!=F_capi) {
    Py_XDECREF(capi_F_tmp); }
  }  /*if (capi_F_tmp == NULL) ... else of F*/
  /* End of cleaning variable F */
  if((PyObject *)capi_G_tmp!=G_capi) {
    Py_XDECREF(capi_G_tmp); }
  }  /*if (capi_G_tmp == NULL) ... else of G*/
  /* End of cleaning variable G */
  if((PyObject *)capi_W_tmp!=W_capi) {
    Py_XDECREF(capi_W_tmp); }
  }  /*if (capi_W_tmp == NULL) ... else of W*/
  /* End of cleaning variable W */
  } /*CHECKSCALAR(len(R)>=N)*/
  } /*if (f2py_success) of N*/
  /* End of cleaning variable N */
  if((PyObject *)capi_R_tmp!=R_capi) {
    Py_XDECREF(capi_R_tmp); }
  }  /*if (capi_R_tmp == NULL) ... else of R*/
  /* End of cleaning variable R */
  } /*if (f2py_success) of IFAULT*/
  /* End of cleaning variable IFAULT */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of SYTOEP *******************************/

/************************************ SPOL ************************************/
static char doc_f2py_rout_dpss_SPOL[] = "\
Function signature:\n\
  SPOL(V,K,IFAULT,[N])\n\
Required arguments:\n"
"  V : input rank-1 array('d') with bounds (N)\n"
"  K : input int\n"
"  IFAULT : input int\n"
"Optional arguments:\n"
"  N := len(V) input int";
/* extern void F_FUNC(SPOL,SPOL)(int*,double*,int*,int*); */
static PyObject *f2py_rout_dpss_SPOL(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int N = 0;
  PyObject *N_capi = Py_None;
  double *V = NULL;
  npy_intp V_Dims[1] = {-1};
  const int V_Rank = 1;
  PyArrayObject *capi_V_tmp = NULL;
  int capi_V_intent = 0;
  PyObject *V_capi = Py_None;
  int K = 0;
  PyObject *K_capi = Py_None;
  int IFAULT = 0;
  PyObject *IFAULT_capi = Py_None;
  static char *capi_kwlist[] = {"V","K","IFAULT","N",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|O:dpss.SPOL",\
    capi_kwlist,&V_capi,&K_capi,&IFAULT_capi,&N_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable IFAULT */
    f2py_success = int_from_pyobj(&IFAULT,IFAULT_capi,"dpss.SPOL() 3rd argument (IFAULT) can't be converted to int");
  if (f2py_success) {
  /* Processing variable K */
    f2py_success = int_from_pyobj(&K,K_capi,"dpss.SPOL() 2nd argument (K) can't be converted to int");
  if (f2py_success) {
  /* Processing variable V */
  ;
  capi_V_intent |= F2PY_INTENT_IN;
  capi_V_tmp = array_from_pyobj(PyArray_DOUBLE,V_Dims,V_Rank,capi_V_intent,V_capi);
  if (capi_V_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(dpss_error,"failed in converting 1st argument `V' of dpss.SPOL to C/Fortran array" );
  } else {
    V = (double *)(capi_V_tmp->data);

  /* Processing variable N */
  if (N_capi == Py_None) N = len(V); else
    f2py_success = int_from_pyobj(&N,N_capi,"dpss.SPOL() 1st keyword (N) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(V)>=N,"len(V)>=N","1st keyword N","SPOL:N=%d",N) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&N,V,&K,&IFAULT);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(V)>=N)*/
  } /*if (f2py_success) of N*/
  /* End of cleaning variable N */
  if((PyObject *)capi_V_tmp!=V_capi) {
    Py_XDECREF(capi_V_tmp); }
  }  /*if (capi_V_tmp == NULL) ... else of V*/
  /* End of cleaning variable V */
  } /*if (f2py_success) of K*/
  /* End of cleaning variable K */
  } /*if (f2py_success) of IFAULT*/
  /* End of cleaning variable IFAULT */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of SPOL ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"DPSS",-1,{{-1}},0,(char *)F_FUNC(DPSS,DPSS),(f2py_init_func)f2py_rout_dpss_DPSS,doc_f2py_rout_dpss_DPSS},
  {"SYTOEP",-1,{{-1}},0,(char *)F_FUNC(SYTOEP,SYTOEP),(f2py_init_func)f2py_rout_dpss_SYTOEP,doc_f2py_rout_dpss_SYTOEP},
  {"SPOL",-1,{{-1}},0,(char *)F_FUNC(SPOL,SPOL),(f2py_init_func)f2py_rout_dpss_SPOL,doc_f2py_rout_dpss_SPOL},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "dpss",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyObject *PyInit_dpss(void) {
#else
#define RETVAL
PyMODINIT_FUNC initdpss(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = dpss_module = PyModule_Create(&moduledef);
#else
  m = dpss_module = Py_InitModule("dpss", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module dpss (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'dpss' is auto-generated with f2py (version:2).\nFunctions:\n"
"  V,SIG,TOTIT,IFAULT = DPSS(NMAX,KMAX,W,SINES,VOLD,U,SCR1,N=len(SINES))\n"
"  SYTOEP(R,G,F,W,IFAULT,N=len(R))\n"
"  SPOL(V,K,IFAULT,N=len(V))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  dpss_error = PyErr_NewException ("dpss.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));



/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"dpss");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
